### ISSUE TITLE
throw error with the small DOM size 

### ISSUE THREAD

**Issue by h2y** [dmester/jdenticon#11]
Thanks for the beautiful project at first.

``` js
        if (size < 30) {
            throw new Error("Jdenticon cannot render identicons smaller than 30 pixels.");
        }
```

But I still catch the error until add the <canvas> size to 34px*34px.

**Comment by dmester** [comment]
Thanks for reporting this issue! The minimum size (despite not being specified in the documentation) actually refers to the size of the icon excluding padding. If not explicitly specifying a padding, it will default to 8%. With 8% padding the actual minimum size is as you've realised 34px. 

```
Specified size: 34px
Actual icon size: 34px - 2 * floor(8% * 34px) = 34px - 2 * floor(2.72px) = 30px
** ok size **

Specified size: 33px
Actual icon size: 33px - 2 * floor(8% * 33px) = 33px - 2 * floor(2.64px) = 29px
** too small **
```

This is not an optimal solution and I will update the documentation of the minimum size to clarify about this issue.

I'm also considering removing the minimum size entirely, leaving that decision to the designer using Jdenticon, but that would probably require some adjustments to the rendering, since the rendering mostly operates on integers.

**Comment by ruchevits** [comment]
I am forced to fork the library because of that minimum size restriction. :(

**Comment by dmester** [comment]
The size limitation is gone since version 1.4.0 which was released today.
