### ISSUE TITLE
Provide a publicly accessible url method of getting a jdenticon

### ISSUE THREAD

**Issue by aarohmankad** [dmester/jdenticon#16]
Something like `http://www.jdenticon.com/generate/name`

**Comment by dmester** [comment]
Thanks for the suggestion! I agree that a public API would be the best solution. It is possible that there will be an official public API for generating PNG and SVG icons in the future, but due to lack of time and that such a service would require a new hosting solution, it probably won't emerge in the nearest future.

**Comment by aarohmankad** [comment]
I've prototyped a quick API based on the current implementation here: http://identicon-api.herokuapp.com/

Let me know what you think! One thing I'd love to see is PNG support on the Node module.

**Comment by dmester** [comment]
Seems really nice! Is it ok if I put a link to your site in the Jdenticon readme?

Regarding PNG support I have recently added support for generating PNG icons natively in the .NET version of the library without any external dependencies. I will have a look at porting the changes to the Javascript version when I have released the new .NET version.

**Comment by aarohmankad** [comment]
That's alright with me!

**Comment by dmester** [comment]
There is now a new release featuring a new method: jdenticon.toPng. It has the same parameters as the toSvg method but outputs a Buffer containing the PNG data stream.

I have not done any performance optimizations, but during my testruns it takes about 10 ms to generate an icon. I probably won't optimize the performance since Jdenticon-net can be used instead if performance is important. Jdenticon-net takes about 1 ms to generate an equal icon.

**Comment by aarohmankad** [comment]
Done!

**Comment by dmester** [comment]
Nice work! Just for your information it seems like the icons are served with the wrong content type and content length. The icons appear to be served with content length 0, the svgs as `text/html` and the pngs as `application/octet-stream`. Chrome has some issues displaying the svg icons on webpages, probably because of the incorrect headers.

![image](https://user-images.githubusercontent.com/9298782/28056737-436f329e-661e-11e7-9717-9f8a6ee0663a.png)

I'm sorry, but regarding hosting it on jdenticon.com, I won't accept any third party requests to host services on the main site at this time.

**Comment by dmester** [comment]
I will close this issue for now since there already is a solution provided by @aarohmankad.

**Comment by Ovi** [comment]
Since the link provided by @aarohmankad is no longer working, we can use [https://dummyjson.com/icon/](https://dummyjson.com/icon/)
Which uses the jdenticon library to generate images.
