### ISSUE TITLE
toPng is a undefined function with react-native!

### ISSUE THREAD

**Issue by violetbobo** [dmester/jdenticon#18]
<img width="483" alt="2017-09-20 1 38 09" src="https://user-images.githubusercontent.com/14857536/30606523-8c336208-9da4-11e7-8fd9-5b1fdd0cd085.png">

```
var jdenticon = require("jdenticon");
var png = jdenticon.toPng("03-5jdfopjp", 100);
```

But toSvg is right!  ahahah,I need png please!

**Comment by dmester** [comment]
Thanks for reporting this issue and sorry for not getting back to you sooner!

Unfortunately toPng is only available in Node.js based environments due to APIs required by [canvas-renderer](https://github.com/dmester/canvas-renderer) that is used to render PNGs. Since React Native is not based on Node.js those APIs are not available and toPng won't work.

Currently there is no plan to incorporate support for React Native into Jdenticon.

I can think of four possible workarounds. I haven't used React Native so I can't tell if they would work, but maybe they might help you getting started.
* Use SVG icons in you React Native app if possible.
* Use [react-native-canvas](https://github.com/iddan/react-native-canvas) or a similar lib emulating a HTML5 canvas context to render the PNG. If you use this approach you need to ensure you include the browser Jdenticon lib located in [dist/jdenticon.js](https://github.com/dmester/jdenticon/blob/master/dist/jdenticon.js). You should them be able to pass a canvas context to Jdenticon [drawIcon](http://jdenticon.com/js-api.html#drawicon) method. You can use the built in [toSvg](https://github.com/dmester/jdenticon/blob/2e7ebd7c7b5c6aa621e0f38c2a8d260a46ce7faf/index.js#L70-L94) method as reference how to use the API.
* Use [Browserify](http://browserify.org/) or [Webpack](https://webpack.js.org/) to create a browser bundle of the Jdenticon Node lib. For this approach you need to use the Node Jdenticon lib (index.js). 
* Fork [canvas-renderer](https://github.com/dmester/canvas-renderer) and replace all native Node API's with JavaScript based replacements.
