### ISSUE TITLE
Jdenticon with Angular

### ISSUE THREAD

**Issue by jeffminsungkim** [dmester/jdenticon#23]
### Objective
I'd like to use [data-jdenticon-hash](https://jdenticon.com/js-api.html#data-jdenticon-hash) attribute with `<img> tag` in Ionic framework (Angular). For instance,

```html
<ion-avatar item-start>
    <img width="80" height="80" data-jdenticon-hash="c92577a190ec8d3be460c76d8e41a4d5">
</ion-avatar>
```

I've tried using the example code below, but it does not work.

**test.html**
```html
<canvas width="100" height="100" data-jdenticon-hash="c92577a190ec8d3be460c76d8e41a4d5"></canvas>
```

**index.html**
```html
<script src="https://cdn.jsdelivr.net/npm/jdenticon@1.8.0" async></script>
```

How can I use Jdenticon in Angular?

**Comment by jeffminsungkim** [comment]
I did figure it out by myself. Closing the issue.

**Comment by mrv777** [comment]
Would you be able to say what you did? 

Thank you!

**Comment by dmester** [comment]
For reference there is a new option called "replaceMode" in version 2.1.0 that will monitor the DOM for icons dynamically inserted by JavaScript frameworks after the initial page load. The option should be set before loading Jdenticon and does not work in IE10 and earlier. [Documentation](https://jdenticon.com/js-api.html#jdenticon-config).

Usage:

```html
<script>
window.jdenticon_config = {
    replaceMode: "observe"
};
</script>
<script src="https://cdn.jsdelivr.net/npm/jdenticon@2.1.0" async></script>
```

This is a new feature in 2.1.0. If you decide to try it, please report any issues.

**Comment by mrv777** [comment]
Using those 2 scripts did not work for me in Angular/Ionic

**Comment by dmester** [comment]
@mrv777: I did some testing in Ionic and got it working with replaceMode:"observe" in two ways. It did however not work if I placed the script elements into a template .html file, since Angular seems to sanitize the source before actually inserting it into the DOM.

If this does not help you, please get back with more information about your setup.
* Do you use canvas or svg elements as icon placeholders? 
* How do you bind values to the elements? 
* How do you load the library?

Please note that I haven't used Angular or Ionic before, so the samples below might not follow best pracises. Also note that I only tested using my desktop browser.

## Method 1: Load Jdenticon as a module
I installed the Jdenticon npm module and imported it into `main.ts` of my app. Then immediately afterwards set the configuration object of the imported module. I didn't use the TypeScript typings for Jdenticon since they are not up to date.

**main.ts**
```ts
import jdenticon from 'jdenticon';
jdenticon.config = {
  replaceMode: "observe"
};
```

Then I inserted icons into a component template as below. Replace VARIABLE_TO_BIND with a proper expression.

**mycomponent.html**
```html
<canvas width="60" height="60" [attr.data-jdenticon-value]="VARIABLE_TO_BIND"></canvas>
```

## Method 2: Script element in entry html file

Insert the following code into the entry html file of the app (index.html):

**index.html**
```html
<script>
window.jdenticon_config = {
    replaceMode: "observe"
};
</script>
<script src="https://cdn.jsdelivr.net/npm/jdenticon@2.1.0" async></script>
```

Then I inserted icons into a component template as below. Replace VARIABLE_TO_BIND with a proper expression.

**mycomponent.html**
```html
<canvas width="60" height="60" [attr.data-jdenticon-value]="VARIABLE_TO_BIND"></canvas>
```
