### ISSUE TITLE
Solid color jdenticons?

### ISSUE THREAD

**Issue by zallarak** [dmester/jdenticon#26]
Is it possible to set a configuration option to obtain solid color jdenticons? For example, like how identicons look on http://identicon.net/

**Comment by dmester** [comment]
Thanks for your suggestion! Is it something like this you need?

![Example](https://jdenticon.com/hosted/issue26.png)

I'm currently planning to add a couple of new configuration options to the next version of Jdenticon, which will make this kind of icons possible.

**Comment by zallarak** [comment]
Yes, that is exactly what I desire. Thank you for your great work on jdenticon.

**Comment by dmester** [comment]
In the just released 2.1.0 there is a new option for controlling the saturation of fields that are normally painted in gray. By setting the same saturation and lightness for colored and grayscale fields you will end up having icons as in my previous post.

You can experiment in the new icon designer:
https://jdenticon.com/icon-designer.html?config=864444000141323237373737

By adjusting both sliders for lightness and saturation so that the have the same value, the icon will be painted in a single color. The code for using the theme is available below the icon configurator.

**Comment by zallarak** [comment]
@dmester really appreciate it!
