### ISSUE TITLE
Purpose of char 9 to 11 of hash?

### ISSUE THREAD

**Issue by dalgard** [dmester/jdenticon#3]
I really like the graphical style and API of this library – good job.

On line [L478](https://github.com/dmester/jdenticon/blob/master/jdenticon.js#L478) you pick out the characters 9 to 11 from the hash. I don't really understand what goes on in this part of the code – can you tell me the visual effect of these three numbers?

Did you mean to pick those chars? When picking the hue, you use the final 7 chars in the hash – to me it would make sense keeping the color information to this part of the hash.

**Comment by dmester** [comment]
Thanks for your feedback! 

Regarding [line 478](https://github.com/dmester/jdenticon/blob/1.2.0/jdenticon.js#L478) each character in the range 9 to 11 is used to determine the color of the identicon. Each identicon consist of 16 shapes in three locations: corner shapes, side shapes and center shapes. The corner shapes will always have the same colors. The same goes with the side shapes and the center shapes. This leaves us with a maximum of three different colors in each identicon. The characters 9 to 11 are converted to an index in the [color array](https://github.com/dmester/jdenticon/blob/1.2.0/jdenticon.js#L450-L461) (with a slightly larger probability for dark gray).

The following [isDuplicate lines](https://github.com/dmester/jdenticon/blob/1.2.0/jdenticon.js#L479-L480) are used to detect if the selected color will lead to an identicon having one of the non-preferred color combinations dark gray+dark color or light gray+light color. The numbers passed as an argument refers to the index ([relative to the color array](https://github.com/dmester/jdenticon/blob/1.2.0/jdenticon.js#L450-L461)) of the forbidden colors in combination. If the selected color from line 478 in combination with the previously selected colors contain at least two of the colors in the forbidden color combination array the function returns true and the selected color is replaced with color index 1, i.e. the mid color (60% lightness).

Regarding your second question that is actually due to a historical fact that a prototype of Jdenticon started out as a fork of [identicon.js](https://github.com/stewartlord/identicon.js), which uses this approach for finding the hue. The Jdenticon code has since then been entirely rewritten but some constructs remain, and I have been reluctant to make changes breaking the appearance of existing identicons.

**Comment by dalgard** [comment]
I understand, thanks a lot for the explanation :+1:
