### ISSUE TITLE
Identical icons

### ISSUE THREAD

**Issue by vishutinov** [dmester/jdenticon#36]
Using as: **jdenticon.toSvg(id, size)** multiple ids generate the same picture

ids (only last digit is different):
5e2782a834f4556f079c5330
5e2782a834f4556f079c5331
5e2782a834f4556f079c5332

generated svg:
`<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 35 35" preserveAspectRatio="xMidYMid meet"><path fill="#ace3db" d="M10 6.5L13.5 3L17 6.5L13.5 10ZM20.5 3L24 6.5L20.5 10L17 6.5ZM24 27.5L20.5 31L17 27.5L20.5 24ZM13.5 31L10 27.5L13.5 24L17 27.5ZM3 13.5L6.5 10L10 13.5L6.5 17ZM27.5 10L31 13.5L27.5 17L24 13.5ZM31 20.5L27.5 24L24 20.5L27.5 17ZM6.5 24L3 20.5L6.5 17L10 20.5Z"></path><path fill="#2e8c7f" d="M3 3L10 3L10 10ZM31 3L31 10L24 10ZM31 31L24 31L24 24ZM3 31L3 24L10 24Z"></path><path fill="#59c7b7" d="M10 10L17 10L17 11.1L14.1 17L10 17ZM24 10L24 17L22.9 17L17 14.1L17 10ZM24 24L17 24L17 22.9L19.9 17L24 17ZM10 24L10 17L11.1 17L17 19.9L17 24Z"></path></svg>`

version: 2.2.0

**Comment by dmester** [comment]
# Short answer
By design. Prepend your ids with any character that is not a valid hexadecimal number to prevent this behavior. The following ids will generate different icons:

```
!5e2782a834f4556f079c5330
!5e2782a834f4556f079c5331
!5e2782a834f4556f079c5332
```

You can see the result in this fiddle:
https://jsfiddle.net/Led53q1a/

# Longer answer

## History
Jdenticon was originally designed to be fed hexadecimal strings created by hash algorithms. Fixed positions of the hash string were, and still are, used to decide icon shapes and colors. For longer hashes, most of the input won't affect the icon at all.

This is normally not an issue since the probability that a decent hash algorithm will produce similar hashes for similar inputs is extremly low. `"xxxxxxxxxx1"` and `"xxxxxxxxxx2"` will produce completely different hashes, despite differing only in a single character. This also means that those values will produce completely different icons, even if Jdenticon will only use fractions of the hashes.

## Introduction of wider input support
To simplify the usage of Jdenticon, an option was later added to support feeding the library any kind of value. Input is since this treated in the following way:

* **Hexadecimal strings > 10 characters** are treated as hash strings according to the description above for backward compatibility.
* **All other values** will be hashed internally using SHA1, and the resulting hash string is fed to the icon generator.

So `jdenticon.toSvg("abc", 100)` is equivalent to `jdenticon.toSvg(SHA1("abc"), 100)`.

## Your example
In your case, each id is a valid hexadecimal string, and will be directly fed to the icon generator, meaning that parts of the string won't be used at all, while specific positions of the string will affect specific shapes and colors of the icon.

This behavior is intentional to prevent affecting icons produced by applications written while Jdenticon only accepted hashes as input.

In this case I would suggest to make the input invalid hexadecimal strings, e.g. by prepending each id with a non-hex character. This will ensure that the ids won't fall into the backward compatibility mode.

## See also
[Are collisions possible for different hashes?](https://github.com/dmester/jdenticon/issues/13#issuecomment-272720294)
