### ISSUE TITLE
Error when trying to use toPng in Angular

### ISSUE THREAD

**Issue by nmehlei** [dmester/jdenticon#42]
I've just installed Jdenticon plus the angular-compatible version inside an angular 10 application. Since I only need the raw image in code without using the angular components, I've just imported the module with

    import { toPng, toSvg } from "jdenticon";

and tried to create a png with

    var png = toPng(userId, 256);

But I keep getting this error:

    ERROR in ./src/app/my-component/my-component.component.ts 53:18-23
    "export 'toPng' was not found in 'jdenticon'

Weirdly, toSvg works without a problem. Is maybe TS typing broken somewhere? Though on first glance I could not see anything wrong with it.

**Comment by dmester** [comment]
I'm afraid [`toPng`](https://jdenticon.com/js-api/M_jdenticon_toPng.html) is only supported on Node.js, and not in browsers. See [documentation](https://jdenticon.com/js-api/M_jdenticon_toPng.html).

There is currently no plan to add PNG support in browsers, since implementing it would require a breaking change to the API, and would also increase the bundle size for those using the UMD distribution.

As a workaround, you can draw the icon onto a canvas, and then let the browser PNG encode the canvas using either [`toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL), or [`toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob).

Here is an example using `toDataURL`:
```
var iconValue = "flkjdhjfhsdgsh";
var iconSize = 200;

var canvas = document.createElement("canvas");
canvas.width = iconSize;
canvas.height = iconSize;
jdenticon.updateCanvas(canvas, iconValue);

var pngDataUri = canvas.toDataURL("image/png");
```
▶ [Run on JSFiddle](https://jsfiddle.net/x0fzLhod/)
