### ISSUE TITLE
Typescript @types/node conflict

### ISSUE THREAD

**Issue by 3axap4eHko** [dmester/jdenticon#45]
file  `node_modules/jdenticon/types/env.d.ts` brings a conflict with `@types/node` by global `interface Buffer { }`

**Comment by dmester** [comment]
The duplicated `Buffer` interface is intentional, to avoid an explicit dependency to `@types/node`. Developers using Jdenticon on Node will most likely reference `@types/node`, and [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) should then take care of merging the interfaces. For developers not using Node, `Buffer` will just resolve to the empty interface.

The reason for not having an explicit dependency to `@types/node` is mainly the `setTimeout` issue, where the [Node declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v15/globals.d.ts#L50) is conflicting with the [browser definition](https://github.com/microsoft/TypeScript/blob/main/lib/lib.webworker.d.ts#L5898).

Do you get an actual build error caused by the interface?

**Comment by dmester** [comment]
Never mind, found out that there are changes to the v16 Node typings breaking the Jdenticon typings. I will have a look at it. Thanks for reporting the issue!

**Comment by dmester** [comment]
Types updated in v3.1.1.
